# Sniperkit-Bot
# - Status: analyzed

language: go
go_import_path: github.com/sniperkit/snk.fork.myke
go:
  - 1.8
install:
  - bin/init.sh
script:
  - gofmt -d -s -e . 2>&1 | tee -a fmt.out
  - test ! -s fmt.out
  - golint -set_exit_status .
  - overalls -project=github.com/sniperkit/snk.fork.myke -covermode=atomic -- -coverpkg=github.com/sniperkit/snk.fork.myke/core,github.com/sniperkit/snk.fork.myke/cmd
  - bin/cross-compile.sh "$TRAVIS_TAG-$TRAVIS_COMMIT"
after_success:
  - mv overalls.coverprofile coverage.txt
  - bash <(curl -s https://codecov.io/bash) -t 5dfb580c-fad8-49bc-93eb-bf758daaca64
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jrQutAMgQgtFNRe1Y/MuONPL0zK0X3uPPywmBuzBrbstbOwOrmKgo0ypogp9wi/1zFbLwe3d7iK22J7m6KOEZaI4iP/53NMvpez/1zylkxEegxIXe6AeHfeMnqrxAcjgNpxun4xuhTjkWmCLP9T5Cn1gQnznIthOS7yGESolO8x1TQ3wTcTwMs/WOPYVtXe66984AOyubT76RtfOag0EKhm5S/h+iMwqj1g5pDeCl8+tNNp9grOOAkSHu/HSx3BtQziMXEhLj2lJZHLAXDYm0NX+A5s+N+Kkgb7awoS5nYHKEzvF4WBMzC9Y5PK0XHv4k8bKb/u3gJXOOCOP9jTKQ45XS7w/xSCUa1k6cIZlGAPdJ/ZL3i5a3RQoeyto/i4+7z3w81jeWNsdWYvGUuJey/w6/I/0nebdj1P1zZsfHjg/B9YFz3O810Vrd1QCjQOIwxmKELp/MRkbmGiutauDxUbdp8jLBITYj2hMoChOowfciM3AAlt9+BgTR02jnXe46MmVO6cQQduDcoFetheNJLPN9qABLauUuto8LrAIkL/QhZ/SFPh2EaWrWx//+PIaquIF4DfIOrg9AfSE1zFr1fvmwOR7GtY7K7kxitu27NL751Bc99RiekJOb+Lk5Uda/wSp9O0hAiRrlPbeNsktqFgov7pxmgE78iEuRbhI7IY=
  file:
    - bin/myke_darwin_amd64
    - bin/myke_linux_amd64
    - bin/myke_windows_amd64.exe
  on:
    repo: sniperkit/snk.fork.myke
    branch: none
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].+$"
notifications:
  email: false
